version: '3'
services:

  # The Application
  app:
    build: docker/app
    container_name: "new-app"
    volumes:
      - ./src:/var/www:cached
    working_dir: /var/www/blog
    depends_on:
      - db
  # The Web Server
  nginx:
    build: docker/nginx
    container_name: "new-nginx"
    working_dir: /var/www/blog
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    depends_on:
      - app
  # The Database
  db:
    image: mysql:5.6
    container_name: "new-db"
    volumes:
      - ./docker/mysql/db-data:/var/lib/mysql:cached
      - ./docker/mysql/mysql_confd:/etc/mysql/conf.d:cached
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "33061:3306"
  #phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "new-phpmyadmin"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=secret
#    restart: always
    links:
      - db
    ports:
      - "8008:80"
    volumes:
      - /sessions
    depends_on:
      - db

volumes:
  db-data:
